spring.datasource.url=jdbc:mysql://localhost:3306/digital_grades?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=digitalgrades_app
spring.datasource.password=${DIGITAL_GRADES_DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=false
