spring.application.name=digital-grades-api
server.port=8080

spring.datasource.url=jdbc:h2:file:./data/digital-grades;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jackson.default-property-inclusion=non_null
